#!/bin/sh

wd="path/to/wd" && cd $wd
ref="path/to/chromosome-level-genome"              #reference
crossover="path/to/co_result"        #merged crossover file generated by hapi, replace the 1st column with the corresponding chromosome
coldspot="path/to/output"         #output file

bin_size=5000000
step=`expr $bin_size / 5`

awk -v OFS='\t' 'NR!=1{print $1,$5,$5}' $crossover \
| bedtools coverage -a <(bedtools makewindows -g "$ref".fai -w $bin_size -s $step | sort -k1,1V -k2,2n -k3,3n) -b - -counts \
| awk -v OFS='\t' '$4==0{print $1,$2,$3}' | bedtools merge | awk '$3-$2>=5000000' > $coldspot

awk '{s+=($3-$2)}END{print s}' $coldspot    #length of coldspot
